spring.application.name=swapi

swapi.base-url=https://www.swapi.tech/api

server.port=${PORT:8080}

app.security.user.name=${APP_USERNAME:swapi}
app.security.user.password=${APP_PASSWORD:swapi123}

app.security.jwt.secret=${JWT_SECRET:jwt-secret-key-1234567890}
app.security.jwt.expiration-minutes=60