create table app_roles (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique,
    description varchar(255),
    created_by varchar(100) not null,
    created_at timestamp not null,
    updated_by varchar(100) not null,
    updated_at timestamp not null
);

create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(100) not null,
    enabled boolean not null,
    created_by varchar(100) not null,
    created_at timestamp not null,
    updated_by varchar(100) not null,
    updated_at timestamp not null
);

create table app_user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_app_user_roles_user foreign key (user_id) references app_users(id) on delete cascade,
    constraint fk_app_user_roles_role foreign key (role_id) references app_roles(id) on delete cascade
);